# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-enterprise-tf-state-bucket-unique-12345"
    dynamodb_table = "terraform-state-lock-table"
    encrypt        = true
    key            = "dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
